### ISSUE TITLE
Breaking change in gsgdt 0.1.3

### ISSUE THREAD

**Issue by bjorn3** [vn-ki/gsgdt-rs#1]
This causes rustc to fail to compile when updating from gsgdt 0.1.2.
```
error[E0599]: no function or associated item named `new` found for struct `gsgdt::Node` in the current scope
  --> /home/bjorn/Projects/rust/compiler/rustc_mir/src/util/generic_graph.rs:59:11
   |
59 |     Node::new(stmts, label, title, style)
   |           ^^^ function or associated item not found in `gsgdt::Node`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_mir`
```

**Comment by MabezDev** [comment]
Just ran into this - the version should be yanked and released as 0.2.0?

**Comment by WilliamVenner** [comment]
Should be yanked and bumped to 1.0.0.

Alternatively just deprecate the `new` function and alias it to the new function.

**Comment by vn-ki** [comment]
I have yanked 0.1.3. I don't have the bandwidth to work on this rn so won't be releasing a new version. If that is enough, can you close this issue?
